version: '2'
checks:
  file-lines:
    enabled: false
  similar-code:
    enabled: false
  method-lines:
    enabled: false
plugins: 
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: .eslintrc.json
      extensions:
        - .es6
        - .js